name: Flutter Build

on:  ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Cache Flutter dependencies
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            /flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - uses: mikefarah/yq@master

      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: 'stable' # Or specify a specific version
          flutter-version-file: pubspec.yaml
          channel: 'stable' # Or specify a specific channel
      - run: flutter pub get

      # Build
      - run: flutter build web --release
      - run: flutter build apk --release
      - run: flutter build windows --release
      # - run: flutter build ios --release --no-codesign

      # Optional: Upload artifacts (e.g., APK, IPA, web build)
      - uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
      - uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/Release-iphoneos
      - uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: build/windows/runner/Release

      # Copy web build to docs folder
      - name: Copy web build to docs
        run: |
          rm -rf docs/*
          cp -r build/web/* docs/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
